SELECT c.CART_ID
FROM CART_PRODUCTS c
INNER JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') y
    ON y.CART_ID = c.CART_ID
INNER JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') m
    ON m.CART_ID = c.CART_ID
GROUP BY CART_ID
ORDER BY CART_ID