SELECT main.ANIMAL_ID, main.NAME
FROM(
SELECT DATEDIFF(ao.DATETIME, ai.DATETIME) date, ai.ANIMAL_ID, ai.NAME
FROM ANIMAL_INS ai
INNER JOIN ANIMAL_OUTS ao ON ao.ANIMAL_ID = ai.ANIMAL_ID
ORDER BY date DESC
    ) main
LIMIT 2