SELECT ch.HISTORY_ID, ROUND((cr.DAILY_FEE * ch.DURATION * ((100 - IFNULL(cp.DISCOUNT_RATE,0))/100)),0) FEE
FROM CAR_RENTAL_COMPANY_CAR cr
INNER JOIN (
    SELECT *, DATEDIFF(END_DATE,START_DATE)+1 DURATION 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) ch ON ch.CAR_ID = cr.car_id AND cr.CAR_TYPE = '트럭'
LEFT JOIN (
    SELECT *, LEFT(DURATION_TYPE,INSTR(DURATION_TYPE,'일')-1) DURATION 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
) cp ON cp.CAR_TYPE = cr.CAR_TYPE AND 
cp.DURATION = (CASE WHEN ch.DURATION BETWEEN 7 AND 29 THEN 7
WHEN ch.DURATION BETWEEN 30 AND 89 THEN 30
WHEN ch.DURATION >= 90 THEN 90 END)
ORDER BY FEE DESC, ch.HISTORY_ID DESC